### ISSUE TITLE
Workshop Kit Components

### ISSUE THREAD

**Issue by Poofjunior** [AllenNeuralDynamics/aind-harp-workshop-materials#2]
@bruno-f-cruz do you think it's worth having a page for these somewhere?

### Workshop Kit Components
* Qty 4x, Wago In-Line Splice Connector, 221-2401, [link](https://www.digikey.com/en/products/detail/wago-corporation/221-2401/16284533)
* Qty 1x, 10K Ohm resistor, RNF14FTD10K0, [link](https://www.digikey.com/en/products/detail/stackpole-electronics-inc/RNF14FTD10K0/17065960)
* Qty 2x, 330 Ohm resistor, RNMF14FTC330R, [link](https://www.digikey.com/en/products/detail/stackpole-electronics-inc/RNMF14FTC330R/2617332)
* Qty 1x, Red/Green bidirectional LED, 5219459F, [link](https://www.digikey.com/en/products/detail/dialight/5219459F/1832557)
* Qty 1x, Photoresistor, NSL-6910, [link](https://www.digikey.com/en/products/detail/advanced-photonix/NSL-6910/5039809)
* Qty 1x, Hall Effect Door Sensor, 59135-030, [link](https://www.digikey.com/en/products/detail/littelfuse-inc/59135-030/154459)
* Qty 1x, Door Sensor Magnet, 57135-000, [link](https://www.digikey.com/en/products/detail/littelfuse-inc/57135-000/43976)

**Comment by bruno-f-cruz** [comment]
Added to the [GettingStarted](https://allenneuraldynamics.github.io/aind-harp-workshop-materials/articles/GettingStarted.html) section. Thanks :)
